CREATE TABLE TBL_SEDE(
                         SEDE_ID NUMERIC(4) NOT NULL PRIMARY KEY,
                         NOMBRE_CORTO VARCHAR2(60) NOT NULL UNIQUE,
                         NOMBRE_LARGO VARCHAR2(400) NULL,
                         ESTADO CHAR(1)DEFAULT '1'
);

CREATE SEQUENCE SEQ_SEDE;

INSERT INTO TBL_SEDE(SEDE_ID,NOMBRE_CORTO, NOMBRE_LARGO) VALUES(SEQ_SEDE.NEXTVAL, 'Lima','Sede Lima');
INSERT INTO TBL_SEDE(SEDE_ID,NOMBRE_CORTO, NOMBRE_LARGO) VALUES(SEQ_SEDE.NEXTVAL, 'San Borja','Sede San Borja');
INSERT INTO TBL_SEDE(SEDE_ID,NOMBRE_CORTO, NOMBRE_LARGO) VALUES(SEQ_SEDE.NEXTVAL, 'Medicentro','Sede Medicentro San Isidro');

COMMIT;